### ISSUE TITLE
не работает на новых процессорах ARM

### ISSUE THREAD

**Issue by MrCoder228re** [ImMALWARE/zapret-magisk#3]
например на oneplus 12 с snapdragon 8 gen 3 не запускается так как binary 32битный я обновил модуль и добавил все возможные архитектуры процессора
посмотреть можно тут https://github.com/MrCoder228re/zapret-magisk
я не знаю как делать pull request поэтому сделал issue

**Comment by MrCoder228re** [comment]
я понял как сделать

**Comment by Fenrir-0xFF** [comment]
@MrCoder228re вот оригинальный скрипт https://github.com/bol-van/zapret/discussions/872 который скомуниздил [ImMALWARE](https://github.com/ImMALWARE) искромсал и добавил в него непроверенный код, что собственно вызвало баги на некоторых прошивках. После чего поддержку Magisk пришлось делать уже мне, до этого скрипт только через TWRP устанавливался.
